### ISSUE TITLE
Remove repository.yml, use Recipes

### ISSUE THREAD

**Issue by dotfloat** [equinor/komodo#106]
Package managers such as nix and Homebrew specify their packages programmatically.

Homebrew:
- **Advanced:** https://github.com/Homebrew/homebrew-core/blob/master/Formula/python.rb
- **Simple:** https://github.com/Homebrew/homebrew-core/blob/master/Formula/libxkbcommon.rb

nix example: https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/python-modules/numpy/default.nix

---
### Komodo recipes example:

Manual example:
```python3
class Python3(Recipe):
    versions = [
        "3.6.9-src"
    ]

    @property
    def source(self):
        version = self.version
        self.from_source = "-src" in version
        if self.from_source:
            version.replace("-src", "")
       
        if self.from_source:
            fmt = "https://www.python.org/ftp/python/{version}/Python-{version}.tgz"
        else:
            fmt = "/project/res/komodo/repository/python-{version}/root"
        return fmt.format(version=version)

    def make(self):
        # CWD is the extracted/git cloned repository
        if self.from_source:
            sh(["./configure", "--prefix="+self.prefix, "--enable-shared,  "--enable-optimizations", "--with-ensurepip=install", "LDFLAGS=-Wl,-rpath={}/lib".format(self.prefix)])
            self.make("install")
        else:
            self.rsync(self.source, self.dest)  # haven't thought through this
```

Advanced example:
```python3
class Libres(CMakeRecipe):
    source = "git+https://github.com/equinor/libecl"
    versions = [
        "4.0.0",
        "3.3.0",
        "3.2.2",
        { name: "3.2.2-overrided-example", source: "https://somewhere.else" }
    ]

    @property 
    def makeopts(self):
        if self.python2:
            return [f"-DSITE_CONFIG_FILE={self.prefix}/etc/ERT/site-packages",
                       "-DINSTALL_ERT_LEGACY=ON",
                       "-DUSE_RPATH=OFF"]
        if self.python3:
            return ["-DUSE_RPATH=OFF"]

    @property
    def dependencies(self):
        extra = []
        if self.python2:
            extra = ["functools32", "futures"]
        return ["PyYAML", "configsuite", "cwrap", "future", "jinja2", "libecl", "numpy", ]
```

Simple example:
```python3
class Numpy(PipRecipe):
    # no source -- default to PyPI
    versions = [
        "1.17.2",
        "1.16.4"
    ]
    dependencies = ["setuptools", "python"]
```

**Comment by dotfloat** [comment]
@jondequinor , you had some strong opinions on this. This avoids copy-paste in `repository.yml` and having to make external bash scripts in order to build more complicated things.

**Comment by jondequinor** [comment]
My opinions were largely formed by a series of komodo meetings, but I'm happy to pass them off as my own.

Completing the dependency graph in komodo would better position us to create tooling that would reduce the size of both the `repository.yml` file and the release files. I think that would to some extent mitigate the _copy/paste_ issue; because when you create a new version or package, you don't drown in redundancy/stale information. See https://github.com/equinor/komodo-releases/issues/103

Generally, I favor a declarative approach over an imperative one any day of the week—twice on Sunday. It is much easier to write tooling on top of static yml-files. And I think we should look closer at the custom builds:

1. How many are *unused*?
1. How many of these custom builds will be nuked once we migrate to RHEL7?
1. How many are hacks that may now have been fixed upstream?

If we're left with 2-3 custom builds that does not fall in any one of the above categories, I think _recipes_ is perhaps unnecessary.

**Comment by dotfloat** [comment]
I do agree that declarative is better than imperative, but that is only if we allocate enough resources to make the declarative approach good. Consider how much copy-pasting is required to bump *libres* and how we wasted a week or so of three people debugging when I copied the incorrect entry.

There's a massive overlap between Python 2 and Python 3 versions of a package (a few dependencies difference), as well as virtually no difference between distinct versions of a package, makes any declarative approach unfeasible without a *lot* of careful planning.

Also consider that, to my knowledge, no other package manager uses declarative configurations to build software, there's no prior reason to think this is a good idea.

I do not think removing stale entries will help this problem, because you only ever look at the top-most entries anyway.

This same problem applies to the release YAML files, but I have no good ideas of how to fix things there.

I also don't really buy the argument of that it's easier to write tooling upon static yml-files rather than code. What's the difference between `yaml_repo[package]["dependencies"]` and `recipe_repo[package].dependencies`?
