### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by hnformentin** [equinor/komodo#257]
Software Innovation Bergen Software Distribution seems not to be an updated title for komodo.

**Comment by kwinkunks** [comment]
Rather than adding a new issue, I'll just add some more updates here.

- The `repository.yml` example is out of date and would not parse.
- The 'Overall goal' section is (and should be) really 'Basic usage', but lacks the actual command required to get `komodo` to build a release. The section could be clearer.
- I think the 'Install' section could be moved up above 'Basic usage'
- The 'Render graph' should provide the command required to do this. But really, these sections are becoming full-blown documentation and should probably be treated as such. Right now, the best thing is probably to put them under "Other examples" or similar.
